name: Flutter Build APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      # Guardamos nuestro código fuente
      - run: cp -r lib /tmp/my_lib && cp pubspec.yaml /tmp/my_pubspec.yaml

      # Generamos la estructura de proyecto Android completa
      - run: flutter create --project-name notepad_glassmorphism .

      # Restauramos nuestro código y pubspec originales
      - run: rm -rf lib && cp -r /tmp/my_lib lib && cp /tmp/my_pubspec.yaml pubspec.yaml

      - run: flutter pub get
      - run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Notepad-APK
          path: build/app/outputs/flutter-apk/app-release.apk
